# Generated by Django 2.1 on 2019-03-19 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Status', models.CharField(choices=[('P', 'Planned'), ('IP', 'InProgress'), ('D', 'Done')], max_length=1)),
                ('Assignee', models.OneToOneField(on_delete='models.CASCADE', related_name='profile_name', to='baseapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('username', models.ManyToManyField(related_name='usernames', to='baseapp.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='task', to='baseapp.Task'),
        ),
        migrations.AddField(
            model_name='comments',
            name='team',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='team', to='baseapp.Team'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='username', to='baseapp.Profile'),
        ),
    ]
